### PR TITLE
Add kitspace.yaml

### PR DESCRIPTION
**Pull request by kasbah**
Hi, I thought this would be a good project for [kitspace.org](https://kitspace.org). It's our open source site that tries to make it easier for people to actually buy the parts and re-build OSHW electronics. I added the kitspace.yaml manifest file that makes sure we pick up the correct files. 

Here is a [preview](http://try-mppt.preview.kitspace.org/boards/github.com/kitspace-forks/mppt-1210-hus/) of what it would look like. If you are happy to add it just merge this. The page would keep updating with this repo in the future (every 3 hours or so). 

The BOM could be improved a bit, in-order to get the 1-click "Buy Parts" links to show up. I would be happy to provide access to the [bom-builder](https://github.com/kitspace/bom-builder) ([more info](https://kitspace.org/bom-builder)) to help you with that (just email me: kaspar@kitspace.org).

### CODE REVIEW

**Comment by martinjaeger** [comment]
Hi @kasbah! Thanks for reaching out.

This sounds very interesting. However, I'm wondering how kitspace works and what its purpose is. Are you getting a cut if someone orders a PCB or parts via kitspace? If yes, how do the original authors or the projects behind the hardware benefit?

Can't really find anything about who/what's behind kitspace.org on the website. In order to merge this I'd like to have some more information.

**Comment by kasbah** [comment]
Hi @martinjaeger, no problem, thanks for asking. The purpose of Kitspace is to promote the replication and practical use of open source hardware electronics. I've written most of the current code-base but we have had some [contributions](https://github.com/kitspace/kitspace/graphs/contributors) over the years. Me/my freelance company is currently financing work on [Kitspace v2](https://github.com/kitspace/kitspace-v2). 

The way the PCB links work is that the PCB services sign up as sponsors on [our Open Collective](https://opencollective.com/kitspace) and as a reward, they get listed (they need to also be able to import a Gerber zip into their quoting interface with one click). Sponsors will soon be asked to pay $300 a year (previously it was $100). The money collected there used to mainly go towards the Octopart API but now my company is providing payment for that too (so we should find something useful to do with the Open Collective money -- maybe some contests or workshops or something like that). For components purchases we don't receive any financial benefit. (I also sell some kits on the [Kitspace shop](https://shop.kitspace.org/).)

The main benefit for project creators is currently visibility for their projects ([our visitor stats are public](https://plausible.io/kitspace.org)) and to make it easier for people to re-build their project by providing easy access to PCB quoting and automatic 1-click parts purchasing (through [our browser extension](https://github.com/kitspace/1clickBOM)). The pages also provide a few other niceties (e.g. easy Gerber inspection, automatic Interactive HTML BOM generation for KiCad and Eagle projects) and I hope having use of the bom-builder tool is regarded as another benefit by project creators. 

With v2 we want to try enabling group-buying PCBs where both Kitspace and project creators would get equal cuts. I'm not sure if this will work though so we'll have to see. 

I hope that clears things up. If not then don't hesitate to ask.

**Comment by martinjaeger** [comment]
Great, thanks for the detailed answer. Looking forward to v2 of kitspace and happy to merge the PR :)

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/libresolar/mppt-1210-hus/

**Pull request merged**
